// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlh7DFu46b9i9alFKdDy4HHAa0LryWAVM',
    appId: '1:248696803883:web:c90d1a2c16507b3707506e',
    messagingSenderId: '248696803883',
    projectId: 'soa-archi',
    authDomain: 'soa-archi.firebaseapp.com',
    storageBucket: 'soa-archi.appspot.com',
    measurementId: 'G-GXL61N5CT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDXsuTohT_ObUlIZarI6HvffDM_eNdOo',
    appId: '1:248696803883:android:a003b1a1704c9ec807506e',
    messagingSenderId: '248696803883',
    projectId: 'soa-archi',
    storageBucket: 'soa-archi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgp3mqR0XKOMrJpFmkwoxx9gNdVwTBNGI',
    appId: '1:248696803883:ios:166c0e1e19775c8407506e',
    messagingSenderId: '248696803883',
    projectId: 'soa-archi',
    storageBucket: 'soa-archi.appspot.com',
    iosBundleId: 'com.example.assone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgp3mqR0XKOMrJpFmkwoxx9gNdVwTBNGI',
    appId: '1:248696803883:ios:99a8a909340cb79807506e',
    messagingSenderId: '248696803883',
    projectId: 'soa-archi',
    storageBucket: 'soa-archi.appspot.com',
    iosBundleId: 'com.example.assone.RunnerTests',
  );
}
